<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query\Expr;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 *
	 * @return array
	 */
	public function sortCarByMake(): array
	{
		$qb = $this->createQueryBuilder('c');
		$qb->orderBy('c.make', 'ASC');
		$qb->select('c')
			->addOrderBy('c.travelledDistance', 'DESC');
		return $qb
			->getQuery()
			->getResult();


	}
	public function getAllCarsAndParts(): array
	{
		// demo Query
		return $this->getEntityManager()->createQuery(
			'SELECT c,p FROM AppBundle:Car c JOIN c.parts p
            ORDER BY c.make ASC, c.model ASC, c.travelledDistance ASC')
			->getResult();
	}
}