<?php

namespace AppBundle\Repository;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 *
	 * @return array
	 */
	public function sortCartByMake(): array
	{
		$qb = $this->createQueryBuilder('c');
		$qb->orderBy('c.model', 'ASC');
		$qb->select('c')
			->addOrderBy('c.travelledDistance', 'DESC');
		return $qb
			->getQuery()
			->getResult();


	}
}