<?php

namespace AppBundle\Repository;


/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * @param string $criteria
	 * @return array
	 */
	public function sortCustomerByBirthDate(string $criteria): array
	{
		$qb = $this->createQueryBuilder('c');
		if ($criteria === 'DESC') {

			$qb->orderBy('c.birthDate', 'DESC');
		} else {
			$qb->orderBy('c.birthDate', 'ASC');
		}

		$qb->select('c')
			->addOrderBy('c.isYoungDriver', 'ASC');
		return $qb
			->getQuery()
			->getResult();




	}
}
