<?php

namespace AppBundle\Repository;

//use AppBundle\Entity\Supplier;

/**
 * SupplierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * @param string $orderByAbroad
	 * @return array
	 */
	public function sortSupplierByAbroad(string $orderByAbroad): array
	{
		$qb = $this->createQueryBuilder('c');
		if ($orderByAbroad === 'True') {
			$qb->where('c.isImporter=True');
		}
		else {
			$qb->where('c.isImporter=False');
		}


//dump($qb);exit;

		return $qb

			->getQuery()
			->getResult();




	}
}
