<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Supplier;

/**
 * SupplierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierRepository extends \Doctrine\ORM\EntityRepository
{
	/**
 * @param string $criteria
 * @return array
 */
	public function sortSupplierByAbroad(string $criteria): array
	{
		$qb = $this->createQueryBuilder('c');
//		if ($criteria === 'LOCAL') {
		$qb->where('c.isImporter=:Locale');

//		}
//		else {
//			$qb->where('c.isImporter=:Importer');
//		}
		$qb->select('c');



		return $qb
			->getQuery()
			->getResult();




	}
}
